version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.4


jobs:
  install:
    docker:
      - image: cimg/ruby:2.7.5-browsers
    resource_class: small
    parallelism: 50
    steps:
      - browser-tools/install-chrome

workflows:
  ilovebrowsing:
    jobs:
      - install
