version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.4


jobs:
  install:
    parameters:
      chrome-version:
        type: string
    docker:
      - image: cimg/ruby:2.7.5-browsers
    steps:
      - browser-tools/install-chrome

workflows:
  ilovebrowsing:
    jobs:
      - install:
          matrix:
            parameters:
              chrome-version:
                - ''
